2025-02-08 18:24:24,734 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-02-08 18:25:48,226 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-02-08 18:27:10,107 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-02-08 18:28:47,093 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-02-08 18:30:21,726 ERROR: Exception on /follow/Stephen1 [POST] [in /Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/app/routes.py", line 383, in follow
    flash('You are following %(username)s!', username=username)
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: flash() got an unexpected keyword argument 'username'
2025-02-08 18:38:14,878 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-02-08 18:38:33,902 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-02-08 18:40:01,489 ERROR: Exception on /reset_password_request [POST] [in /Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/app/routes.py", line 309, in reset_password_request
    send_password_reset_email(user) # if there is such an email given by the user, send an automated email
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/stephentrento/flask_app/app/email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/Users/stephentrento/flask_app/app/models.py", line 130, in get_reset_password_token
    return jwt.encode(
           ^^^^^^^^^^
AttributeError: module 'jwt' has no attribute 'encode'
2025-02-08 18:47:56,918 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-02-08 18:48:10,595 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-02-08 18:48:29,806 ERROR: Exception on /reset_password_request [POST] [in /Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/app/routes.py", line 309, in reset_password_request
    send_password_reset_email(user) # if there is such an email given by the user, send an automated email
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/stephentrento/flask_app/app/email.py", line 24, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
              ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              user=user, token=token),
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2025-02-08 19:10:02,002 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-02-08 19:28:56,659 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
