2025-01-26 18:05:09,598 ERROR: Exception on / [GET] [in /Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: user.wants_to_be_organiser

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 915, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 1291, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/Users/stephentrento/flask_app/app/routes.py", line 15, in before_request
    if current_user.is_authenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
                    ~~~~~^^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ~~~~~~~~~^^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
  File "/Users/stephentrento/flask_app/app/models.py", line 125, in load_user
    return db.session.get(User, int(id))
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/sqlalchemy/orm/scoping.py", line 1058, in get
    return self._proxied.get(
           ~~~~~~~~~~~~~~~~~^
        entity,
        ^^^^^^^
    ...<6 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 3694, in get
    return self._get_impl(
           ~~~~~~~~~~~~~~^
        entity,
        ^^^^^^^
    ...<7 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 3874, in _get_impl
    return db_load_fn(
        self,
    ...<5 lines>...
        bind_arguments=bind_arguments,
    )
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/sqlalchemy/orm/loading.py", line 694, in load_on_pk_identity
    session.execute(
    ~~~~~~~~~~~~~~~^
        q,
        ^^
    ...<2 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<4 lines>...
        conn,
        ^^^^^
    )
    ^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
        statement, params or {}, execution_options=execution_options
    )
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.wants_to_be_organiser
[SQL: SELECT user.id AS user_id, user.wants_to_be_organiser AS user_wants_to_be_organiser, user.access_level AS user_access_level, user.organisation AS user_organisation, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen 
FROM user 
WHERE user.id = ?]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-26 18:05:25,894 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 18:06:15,350 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 18:06:21,276 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 18:06:58,040 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 18:08:49,796 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 18:08:59,125 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 19:01:49,890 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 19:02:09,353 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 19:02:41,277 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 19:03:44,465 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 19:06:41,997 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 19:09:55,301 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 19:10:04,533 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 19:10:15,336 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 19:10:52,595 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 19:15:42,571 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 19:15:55,755 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 19:19:07,367 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 19:20:44,727 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 19:20:59,310 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 19:21:28,198 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
2025-01-26 22:08:57,404 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:48]
