2025-01-31 11:06:45,966 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 11:10:46,999 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 11:15:01,203 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 11:20:26,263 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 11:22:31,812 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 11:23:07,473 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 13:34:20,653 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 13:39:17,099 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 13:39:23,279 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 13:46:36,199 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 13:52:54,396 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 13:59:25,136 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 13:59:35,387 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 13:59:58,748 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 14:00:34,540 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 14:00:44,842 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 14:01:08,206 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 14:06:39,727 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 14:07:01,506 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 14:07:47,332 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 14:07:51,711 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 14:07:57,400 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 14:08:09,555 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 14:14:30,805 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 14:14:40,555 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 14:15:21,074 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 14:16:34,624 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 14:17:53,346 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 21:25:12,863 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 21:26:52,053 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 21:27:01,508 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 21:29:16,369 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 21:29:44,885 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 21:30:08,590 ERROR: Exception on /login [POST] [in /Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/app/routes.py", line 211, in login
    sa.select(User).where(User.username == form.username.data)) # let user = the first match where username entered matches a username in the db
                          ^^^^^^^^^^^^^
AttributeError: type object 'User' has no attribute 'username'. Did you mean: 'Username'?
2025-01-31 21:32:03,855 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 21:48:16,248 INFO: Microblog startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-01-31 21:49:10,344 ERROR: Exception on /map [GET] [in /Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/app/routes.py", line 119, in map
    form = EventForm()
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/wtforms/form.py", line 209, in __call__
    return type.__call__(cls, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask_wtf/form.py", line 73, in __init__
    super().__init__(formdata=formdata, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/wtforms/form.py", line 281, in __init__
    super().__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/wtforms/form.py", line 49, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/wtforms/meta.py", line 28, in bind_field
    return unbound_field.bind(form=form, **options)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/wtforms/fields/core.py", line 387, in bind
    return self.field_class(*self.args, **kw)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/wtforms/fields/datetime.py", line 170, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/wtforms/fields/datetime.py", line 30, in __init__
    super().__init__(label, validators, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Field.__init__() got an unexpected keyword argument 'filter_type'
